.TH execdir 1 "2022-07-13" "execdir"

.SH NAME
execdir \- execute a command in a specific directory 

.SH SYNOPSIS
\fBexecdir\fR [\fB-h\fR] [\fB-v\fR] [\fB-s\fR] [\fB-a\fR \fINAME\fR \fIPATH\fR] [\fB-r\fR \fINAME\fR] [\fB-l\fR] [\fIARGS\fR...]

.SH DESCRIPTION
\fBexecdir\fR is a tool that lets you run a command in a specific directory. It supports shell commands and path aliases. \fBexecdir\fR will try to get an alias if path doesn't exist.

There is also a symlink called \fBx\fR, so you can type less using it.

.SH OPTIONS

.IP "\fB-h\fR"
Display the help message and exit

.IP "\fB-v\fR"
Display the version number of execdir and exit

.IP "\fB-s\fR"
Execute the command as a shell command

.IP "\fB-a\fR \fINAME\fR \fIPATH\fR"
Create an alias for a path

.IP "\fB-r\fR \fINAME\fR"
Delete an alias

.IP "\fB-l\fR"
List all aliases

.SH EXECDIR FILE

All aliases are defined in the \fB~/.execdir\fR file. Each line contains an alias name and a path delimited by a colon:

    name:path

.SH AUTHOR
Gustavo Costa <xfgusta@gmail.com>

.SH BUGS
Report bugs to <https://github.com/xfgusta/execdir/issues>

.SH COPYRIGHT
Copyright (c) 2022 Gustavo Costa
