.TH execdir 1 "2022-06-23" "execdir"

.SH NAME
execdir \- execute a command in a specific directory 

.SH SYNOPSIS
\fBexecdir\fR [\fB--help\fR] [\fB--version\fR] [\fB-s\fR] [\fIpath\fR] [\fIcommand\fR...]

.SH DESCRIPTION
\fBexecdir\fR is a tool that lets you run a command in a specific directory.

.SH OPTIONS

.IP "\fB-s\fR, \fB--shell\fR"
Execute the command as a shell command

.IP "\fB--help\fR"
Display the help message and exit

.IP "\fB--version\fR"
Display the version number of execdir and exit

.SH AUTHOR
Gustavo Costa <xfgusta@gmail.com>

.SH BUGS
Report bugs to <https://github.com/xfgusta/execdir/issues>

.SH COPYRIGHT
Copyright (c) 2022 Gustavo Costa